version: '3.8'

networks:
  private:
    driver: bridge
    
volumes:
  hacker-seed:
    name: blockchain_${NAME}_shared_vol

services:
  chall-servers:
    build: ./servers/
    image: blockchain_${NAME}_servers:latest
    container_name: blockchain_${NAME}_servers
    environment:
      - ELECTRS_PORT=${ELECTRS_PORT}
    expose:
      - ${SERVER_PORT}/tcp
      - ${ELECTRS_PORT}/tcp
    ports:
      - ${ELECTRS_PORT}:${ELECTRS_PORT}
    volumes:
      - ./servers/bitcoin-25.0:/bitcoin-core:ro
      - ./servers/server.py:/server.py:ro
      - ./configs/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro
      - ./configs/electrs.conf:/electrs.conf:ro
      - ./scripts/servers-entrypoint.sh:/entrypoint.sh:ro
      - ./scripts/generate_blocks.sh:/generate_blocks.sh:ro
      - hacker-seed:/shared
    healthcheck:
      test: "curl --fail http://blockchain_${NAME}_servers:${SERVER_PORT}/env/ELECTRS_PORT || exit 1"
      start_period: 5s
      timeout: 5s
      retries: 2
      interval: 60s
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - private

  chall-handlers:
    depends_on:
      chall-servers:
        condition: service_healthy
    build: ./handlers/
    image:  blockchain_${NAME}_client:latest
    container_name: blockchain_${NAME}_client
    environment:
      - NAME=${NAME}
      - ELECTRS_IP=${ELECTRS_IP}
      - ELECTRS_PORT=${ELECTRS_PORT}
      - HANDLER_PORT=${HANDLER_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - FLAG=${FLAG}
    expose:
      - ${HANDLER_PORT}/tcp
    ports:
      - ${HANDLER_PORT}:${HANDLER_PORT}
    volumes:
      - ./scripts/handlers-entrypoint.sh:/entrypoint.sh:ro
      - ./handlers/00-create-xinetd-service:/startup/00-create-xinetd-service:ro
      - ./handlers/99-start-xinetd:/startup/99-start-xinetd:ro
      - ./handlers/start-handler.sh:/home/chall/start-handler.sh:ro
      - ./handlers/handler.py:/home/chall/handler.py:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - private

  chall-instance:
    depends_on:
      - chall-servers
      - chall-handlers

    build: 
      context: ./gameinstance/
      args: 
        - SSH_PORT=${SSH_PORT}
        - SSH_USER=${HACKER_SSH_USER}
        - SSH_PWD=${HACKER_SSH_PWD}
    image: blockchain_${NAME}_gameinstance:latest
    container_name: blockchain_${NAME}_gameinstance
    hostname: mywallet
    env_file:
      - .env
    tty: true
    expose:
      - 22/tcp
    ports:
      - ${SSH_PORT}:${SSH_PORT}
    volumes:
      - hacker-seed:/home/${HACKER_SSH_USER}/
    restart: unless-stopped
